#ifndef COMMON_HPP
#define COMMON_HPP

enum N64CONTROLLER_BUTTON
{
    N64CONTROLLER_BUTTON_A = 0,
    N64CONTROLLER_BUTTON_B,
    N64CONTROLLER_BUTTON_START,
    N64CONTROLLER_BUTTON_DPAD_UP,
    N64CONTROLLER_BUTTON_DPAD_DOWN,
    N64CONTROLLER_BUTTON_DPAD_LEFT,
    N64CONTROLLER_BUTTON_DPAD_RIGHT,
    N64CONTROLLER_BUTTON_CBUTTONS_UP,
    N64CONTROLLER_BUTTON_CBUTTONS_DOWN,
    N64CONTROLLER_BUTTON_CBUTTONS_LEFT,
    N64CONTROLLER_BUTTON_CBUTTONS_RIGHT,
    N64CONTROLLER_BUTTON_LEFTTRIGGER,
    N64CONTROLLER_BUTTON_RIGHTTRIGGER,
    N64CONTROLLER_BUTTON_ZTRIGGER,
    N64CONTROLLER_NUM
};

#endif // COMMON_HPP
